### ISSUE TITLE
Reject objectAlias with .. in the path 

### ISSUE THREAD

**Issue by aramase** [aws/secrets-store-csi-driver-provider-aws#13]
- Add validation for `objectAlias` to reject reserved paths `../`

Reference: https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/384

**Comment by joebaro** [comment]
Thank you for opening this issue. This plugin is not vulnerable to path traversal because it first writes the secret to a temp file in the mount directory and then [renames it](https://github.com/aws/secrets-store-csi-driver-provider-aws/blob/main/server/server.go#L265) using ```os.Rename()``` which will fail with "pattern contains path separator" if either the objectAlias or objectName contain a path separator. There is also a [unit test](https://github.com/aws/secrets-store-csi-driver-provider-aws/blob/main/server/server_test.go#L513-L538) to verify this behavior.

Just to be certain, I also re-verified this with a hand test too.
```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets
spec:
  provider: aws
  parameters:
    pathTranslation: "False"
    objects: | 
        - objectName: "BinarySecret"
          objectAlias: "../BinarySecret"
```

```
$ kubectl describe pod ...

    ...
  Warning  FailedMount  8s (x6 over 25s)  kubelet, ip-10-0-184-216.us-west-2.compute.internal  MountVolume.SetUp failed for volume "secrets-store-inline" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Unknown desc = failed to mount secrets store objects for pod default/my-deployment-5ff956f4cb-46whx, err: rpc error: code = Unknown desc = pattern contains path separator
```
