### ISSUE TITLE
Establish which Helm chart should be used and maintained

### ISSUE THREAD

**Issue by pclalv** [aws/secrets-store-csi-driver-provider-aws#135]
https://github.com/aws/secrets-store-csi-driver-provider-aws/pull/123 add a Helm chart to this repo. [pierluigilenoci](https://github.com/pierluigilenoci) has pointed out several times, to no avail ([(1)](https://github.com/aws/secrets-store-csi-driver-provider-aws/pull/123#issuecomment-1257624744), [(2)](https://github.com/aws/secrets-store-csi-driver-provider-aws/issues/15#issuecomment-1257627326)), that this seems to duplicate [an existing chart in the aws/eks-charts repo](https://github.com/aws/eks-charts/tree/master/stable/csi-secrets-store-provider-aws). I feel pierluigilenoci's concern, and I feel further concerned that maintainers haven't yet addressed that concern.

in particular, I'm concerned as to how users will be effected by this situation of having two charts. now that there are two charts to choose between, users wanting to use an upstream chart have to ask themselves which one they'll use (there's always the option of maintaining one's own chart, but to argue that users should write their own is to argue against the availability of the existing charts as anything more than an example to possibly follow). these charts seek to do the same thing, and there's no clear "official" recommendation on which to use or why. a big danger here is that users of one chart will someday find that their chart is no longer supported, because AWS has figured out that two charts that seek to do the same exist and that it's a waste of time to maintain both; then those unlucky users will have to waste their time migrating to the other chart.

**Comment by jaypipes** [comment]
@pclalv @pierluigilenoci Hi there, apologies for the delayed response on this. I met with the ASM team today to discuss how to move forward with the Helm Chart for the asm secrets-store provider.

Our end goal is to have a single Helm chart and have that Helm chart be maintained by the team that is responsible for `github.com/aws/secrets-store-csi-driver-provider-aws`. Many of the other Helm charts in the `github.com/aws/eks-charts` repository are actually *mirrored* from the source code repository that stores the container image that is installed by the Helm chart.

An example of this is the Node Termination Handler (NTH), which has the canonical Helm chart contained in the [`github.com/aws/aws-node-termination-handler`](
secrets-store-csi-driver-provider-aws) source repository (in the [`config/helm/`](https://github.com/aws/aws-node-termination-handler/tree/main/config/helm) directory. The NTH repository has a [script that syncs](https://github.com/aws/aws-node-termination-handler/blob/main/scripts/sync-to-aws-eks-charts) that Helm chart to the [`github.com/aws/eks-charts/stable/aws-node-termination-handler`](https://github.com/aws/eks-charts/tree/master/stable/aws-node-termination-handler) directory.

The ASM team is going to get a proper `README.md` file in shape for their Helm chart, add the syncing script to the github.com/aws/secrets-store-csi-driver-provider-aws` repository and increment the Helm Chart Version to use a new major version (e.g. `v1.0.0` since the Chart Version of the eks-charts current Helm chart version is [`v0.0.3`](https://github.com/aws/eks-charts/blob/a7b3d854e2eb95edaa1bbd48eb3fd0e4d49ed7f1/stable/csi-secrets-store-provider-aws/Chart.yaml#L3). Once this is done, we will activate the syncing script and there will only be a single Helm chart for the CSI secrets store driver provider-aws.

Hope that makes sense, and apologies for the long and delayed responses.

**Comment by pclalv** [comment]
thanks for bringing your attention to this, @jaypipes, I do appreciate it. your response comes timely enough for me, so don't worry about that.

that mostly sounds good to me. 

do you mean that the chart in this repo will become the one true chart? if so, why? the `aws/eks-charts` chart is much older and therefore likely have more users; in that case, more users may be affected by dropping support for that chart. Pierluigi also claims that it's more feature-rich than this one. I have to admit that that those are almost certainly not the only concerns in making this decision, but they seem clear and of some importance, to me.

**Comment by pierluigilenoci** [comment]
@jaypipes about a year and a half ago I did a [PR](https://github.com/aws/secrets-store-csi-driver-provider-aws/pull/35) in this repository with [a lot of difficulties](https://github.com/aws/secrets-store-csi-driver-provider-aws/pull/35#issuecomment-986966683).

After months that no one giving me feedback, I tried to open [another one](https://github.com/aws/eks-charts/pull/651) in the EKS Chart repo with more luck.

The one that I now find [here](https://github.com/aws/secrets-store-csi-driver-provider-aws/tree/main/charts/secrets-store-csi-driver-provider-aws) in my opinion has several critical issues that I have already raised in some comments ([1](https://github.com/aws/secrets-store-csi-driver-provider-aws/pull/123#issuecomment-1257624744),[2](https://github.com/aws/secrets-store-csi-driver-provider-aws/pull/123#issuecomment-1257659602),[3](https://github.com/aws/secrets-store-csi-driver-provider-aws/issues/15#issuecomment-1257627326)). 

Obviously, AWS is a private company and can do whatever it wants. 
Still, I strongly suggest realigning the new chart to the features already present in the old one (which is already published on [ArtifactHub.io](https://artifacthub.io/packages/helm/aws/csi-secrets-store-provider-aws)).

**Comment by pierluigilenoci** [comment]
@simonmarty apart from the PSP the ones that leaped to my eyes are

- The [driver](https://github.com/kubernetes-sigs/secrets-store-csi-driver) cannot be installed as a dependency
- There is no way to configure the `imagePullSecrets` so it is not possible to use a custom image
- `appVersion` is missing

**Comment by simonmarty** [comment]
We're discussing these feature requests internally. If we can't implement them for some reason, we'll make sure to warn users before the switch.

**Comment by luckielordie** [comment]
> The ASM team is going to get a proper `README.md` file in shape for their Helm chart, add the syncing script to the `github.com/aws/secrets-store-csi-driver-provider-aws` repository and increment the Helm Chart Version to use a new major version (e.g. `v1.0.0` since the Chart Version of the eks-charts current Helm chart version is [`v0.0.3`](https://github.com/aws/eks-charts/blob/a7b3d854e2eb95edaa1bbd48eb3fd0e4d49ed7f1/stable/csi-secrets-store-provider-aws/Chart.yaml#L3). Once this is done, we will activate the syncing script and there will only be a single Helm chart for the CSI secrets store driver provider-aws.

I don't know how welcome my input will be since it's a bit minor.

Since [Helm uses the SemVer scheme for its versioning](https://helm.sh/docs/topics/release_policy/#semantic-versioning) it's perfectly reasonable to only bump the minor version until you're happy that the API(in this case `values.yaml`) is stable enough to commit to a full major release. Pre version 1 any minor bump can be API breaking as it's understood in sections 4 and 5 of the [spec](https://semver.org/spec/v2.0.0.html#spec-item-4).

I'm cursed to have spent far too long studying the spec for a project so here we are!

**Comment by simonmarty** [comment]
The chart hosted on `eks-charts` was marked as deprecated in version `0.0.4`. We've opened internal feature requests for differences between our chart and the one hosted on `eks-charts`.
