### ISSUE TITLE
Feature request: Cross account fetching of secrets

### ISSUE THREAD

**Issue by tirsen** [aws/secrets-store-csi-driver-provider-aws#19]
Is it possible to fetch secrets from SecretsManager in another account using cross account access?

**Comment by joebaro** [comment]
Yes. Using the driver is no different than any other Secrets Manager API request. You will have to [setup the secret for cross account access](https://aws.amazon.com/blogs/database/design-patterns-to-access-cross-account-secrets-stored-in-aws-secrets-manager/) making sure to setup the [resource policy](https://docs.amazonaws.cn/en_us/secretsmanager/latest/userguide/auth-and-access_resource-based-policies.html) to grant access and the [IRSA role](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) to grant access (both are required for cross account access). In the SecretProviderClass when you specify the secret you have to use the full ARN including the account Id. Note that you will probably want to also use the objectAlias declaration to change the name used to mount the secret, otherwise the mounted name will be the full ARN.

**Comment by erikkn** [comment]
@tirsen , did you manage to get this to work :)?

**Comment by tirsen** [comment]
Sorry for the late reply. No I did not. What does this mean?
> In the SecretProviderClass when you specify the secret you have to use the full ARN including the account Id.

I can't change the `eks.amazonaws.com/role-arn` annotation of the pods that will read the secrets because that role is used to access resources in the same account. How can I specify which role to use for accessing the secrets without changing the IAM role of the service account?

**Comment by tirsen** [comment]
I've changed the title and the description of the issue. Can we please re-open this as I believe this is not currently supported by the CSI driver.

**Comment by erikkn** [comment]
I can actually confirm that one can pull/retrieve cross-account secrets, but make sure there is no `/` included in the secret name.

**Comment by tirsen** [comment]
Yes it is possible to pull secrets from another account but you have to change the IRSA role of the pod to be the role of the other account right?

**Comment by erikkn** [comment]
> but you have to change the IRSA role of the pod to be the role of the other account right?
No, this is not necessary. Just make sure that the (resource) policy attached/associated with your actual secret allows the right set of principals (e.g. your role or the entire account).

**Comment by tirsen** [comment]
I think I understand now. Let me try that!

**Comment by erikkn** [comment]
Of course you will also have to associate an IAM role with your Pod(s) :-)

**Comment by jland-redhat** [comment]
So is this possible? I am trying to do something similar now and having trouble.
