### ISSUE TITLE
Image secrets-store-csi-driver-provider-aws is unsupported in AWS ECR scan

### ISSUE THREAD

**Issue by Govind10g** [aws/secrets-store-csi-driver-provider-aws#209]
Hi Team,

We are unable to scan image - **secrets-store-csi-driver-provider-aws**, tag - 1.0.r2-42-ga2fd202-2023.03.03.20.03.
It is showing unsupported image in ECR scan report. 

Could you please see on this and enable image to scan it in AWS ECR. 
We have to scan this image  before moving to production. 

Best Regards,
Govind Gupta

**Comment by simonmarty** [comment]
Amazon ECR does not support scanning images built from the [Docker scratch](https://hub.docker.com/_/scratch) image.

This is because the ECR scanner scans the operating system the container runs on. No need to scan anything if the container does not contain an operating system. [Docs here](https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-scanning-troubleshooting.html)
