### ISSUE TITLE
Env in pod is not loading as expected 

### ISSUE THREAD

**Issue by nihit001raj** [aws/secrets-store-csi-driver-provider-aws#295]
I am using below secretproviderclass and it is creating secret and loading it as an env in pod but the format is not correct.

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: pp-dev-pp-webapp
  namespace: pp-dev
spec:
  provider: aws
  secretObjects:
  - secretName: csi-secret-newrelic
    type: Opaque
    data:
    - key: NEW_RELIC_LICENSE_KEY
      objectName: NEW_RELIC_LICENSE_KEY
  parameters:
    objects: |
        - objectName: "arn:aws:secretsmanager:us-east-1:1xxxxxx:secret:xxxxxxxx"
          objectAlias: "NEW_RELIC_LICENSE_KEY"
          objectType: "secretsmanager"
..
..
..

volumes:
      - name: pod-webapp
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "pp-dev-pp-webapp"
      containers:
        - name: {{ include "helm.name" . }}
          image: {{ .Values.imageRepository }}/{{ .Values.imageName }}:{{ .Values.imageTag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          volumeMounts:
           - name: pod-webapp
             mountPath: "/mnt"
             readOnly: true
          env:
          - name: test_name
            valueFrom:
              secretKeyRef:
                name: csi-secret-newrelic
                key: NEW_RELIC_LICENSE_KEY
..
..
..
The env is loading in below format

test_name={"NEW_RELIC_LICENSE_KEY":"xxxxxxxxxxxxxxxx"}

but it should be in format

NEW_RELIC_LICENSE_KEY":"xxxxxxxxxxxxxxxx

Tried editing secretstoredriver and deployment by commenting out test_name reference but it did not help

**Comment by YuvalShAz** [comment]
Hi nihit001raj, I have looked into this issue and have reproduced the behavior you detail in your comment with a few key assumptions:

1. I assume your secret is JSON in nature (this is because of how your env is currently loading: {"NEW_RELIC_LICENSE_KEY":"xxxxxxxxxxxxxxxx”})
2. I assume all-else-equal re: the choice of image, image pull policy, etc… (between your implementation and mine)
3. I assume that when you “comment[ed] out test_name” you had added it back in somewhere else. This field is needed or the following error is reported: 
![unknown](https://github.com/aws/secrets-store-csi-driver-provider-aws/assets/159810020/1b0a6d91-5b77-4f5a-8567-24b13d1ed2d2)

Given these assumptions my conclusion is that you most likely need to use the _jmesPath_ parameter when ingesting a secret object (ctrl-f “jmesPath” in [README.md](https://github.com/aws/secrets-store-csi-driver-provider-aws/blob/main/README.md)). This automatically parses your json secret and gives each [key-path](https://jmespath.org/specification.html) you have specified an alias which can be used to create a kube-secret which can then be used to create an env variable. (This produces the behavior **NEW_RELIC_LICENSE_KEY":"xxxxxxxxxxxxxxxx)**

Without using this _jmesPath_ specifier, the secret will indeed be ingested as if it were a raw string (not json formatted) and loaded into the env with the name you specify in the deployment file. (This produces the behavior **test_name={"NEW_RELIC_LICENSE_KEY":"xxxxxxxxxxxxxxxx”})**
