### ISSUE TITLE
secrets is forbidden

### ISSUE THREAD

**Issue by upa-mihir07** [aws/secrets-store-csi-driver-provider-aws#76]
secrets is forbidden user **_system:serviceaccount:kube-system:secrets-store-csi-driver_** 

What could be the issue here?

Logs
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/44435981/163120083-17b05461-d9c0-43ac-b829-1ec9f9619e92.png">

**Comment by simonmarty** [comment]
Best guess is the error is thrown [here](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/7ac887a55786306157ad308c751dc1c1fc064fdf/controllers/secretproviderclasspodstatus_controller.go#L299) by the [Secrets Store CSI Driver](https://github.com/kubernetes-sigs/secrets-store-csi-driver). It does not look like the error is caused by our AWS provider.
